### ISSUE TITLE
Give option to show bars next to each other

### ISSUE THREAD

**Issue by stevsimo** [coodoo-io/coo_charts#7]
Give the option to show the bars next to each other instead of on top of each other.
![Screenshot 2023-10-27 at 13 09 03](https://github.com/coodoo-io/coo_charts/assets/47678184/29566f31-2d6e-44eb-8d0f-baf601cba2c0)

**Comment by mkuehle** [comment]
is already fixed
<img width="1487" alt="image" src="https://github.com/coodoo-io/coo_charts/assets/1588566/f9fa48f2-58d8-4470-a71f-73b5318ab586">

**Comment by mkuehle** [comment]
fixed
<img width="1487" alt="image" src="https://github.com/coodoo-io/coo_charts/assets/1588566/7efe5500-bb3d-45b9-8b85-ba26482d1934">
